apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.image.repository }}/overengineered-api-gateway:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: GCP_HEALTH_API_URL
              value: {{ .Values.apiGateway.gcpHealthApiUrl | quote }}
          resources:
            requests:
              cpu: {{ .Values.apiGateway.resources.requests.cpu | quote }}
              memory: {{ .Values.apiGateway.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.apiGateway.resources.limits.cpu | quote }}
              memory: {{ .Values.apiGateway.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
