apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.mongodb.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              cpu: {{ .Values.mongodb.resources.requests.cpu | quote }}
              memory: {{ .Values.mongodb.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.mongodb.resources.limits.cpu | quote }}
              memory: {{ .Values.mongodb.resources.limits.memory | quote }}
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
