apiVersion: v1
kind: Service
metadata:
  name: metrics-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: metrics-api
  ports:
    - port: 3002
      targetPort: 3002
