apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-deployment
  namespace: overengineered
  labels:
    app: metrics-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      name: metrics-api
      labels:
        app: metrics-api
    spec:
      containers:
        - name: metrics-api
          image: johnhopedawa/overengineered-metrics-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
